### ISSUE TITLE
The package is expecting object when creating a bill using array. 

### ISSUE THREAD

**Issue by khrnchn** [tarsofttech/toyyibpay-laravel#7]
https://flareapp.io/share/B5ZAb9g7

**Comment by aleprosli** [comment]
Hye @khrnchn,

You can **convert array to object**, and send param to create bill

![image](https://github.com/tarsofttech/toyyibpay-laravel/assets/72934759/d58f46b5-939d-4312-86ba-1ad191dfabaf)

**Can refer :**

1. Tutorial Video [Here!](https://youtu.be/DmCaI91bS-w?t=1184) - Minute 19:44
2. [Stackoverflow - Convert an array to object](https://stackoverflow.com/questions/1869091/how-to-convert-an-array-to-object-in-php)

Tqvm

**Comment by khrnchn** [comment]
thanks, i have used this code previously thanks to Mr Tarmizi.

**Comment by samtarmizi** [comment]
hi, im gonna closed the issue as the issue resolve on #8 ya. have a nice day everyone
